1. Write a function to compute 5/0 and use try/except to catch the exceptions.


In [14]:
def compute():
    try:
        result=5/0
        print(result)
            
    except:
        print("cannot divide by 0")
    else:
        print("successfull computation")
    finally:
        print("You're here anyway!")
        
compute()
    

cannot divide by 0
You're here anyway!


2. Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]


In [5]:
subject=["Americans","Indians"]
verb=["Play", "watch"]
objects=["baseball","Cricket"]
result=[(subjects+" "+verbs+" "+obj) for subjects in subject for verbs in verb for obj in objects ]
for res in result:
    print(res)

Americans Play baseball
Americans Play Cricket
Americans watch baseball
Americans watch Cricket
Indians Play baseball
Indians Play Cricket
Indians watch baseball
Indians watch Cricket


In [7]:
import numpy as np

Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre               Theophile Vandermonde. 

In [11]:
def vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-i-1) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx


inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = vander_matrix(inputvector,no_col_opmat,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

